### ISSUE TITLE
Tracker: Improvements to command output analysis #6

### ISSUE THREAD

**Issue by SeanHeelan** [elastic/sysgrok#1]
# ToDo
- [x] Allow the user to provide a problem without command inputs and use the LLM to suggest commands to run
- [x] Add a mode where the tool actually executes the command(s), e.g. either via a command provided on the command line, or via an input file that lists the commands to run. 
- [x] Build a baseline input file containing a set of commands to run (possibly use GPT itself to suggest them) 
- [x] Add a mode where the tool can connect to a machine via ssh to run commands
- [x] Fix the prompt so that the output structure is more precisely defined (by example, or by template) 
- [x] Add token counting to the input, and try to ensure that there are sufficient tokens available for the response. 
- [x] Figure out if there's any benefit to combining the outputs from multiple CLI tools into a single prompt. Would the model be able to better detect issues if, for example, it had data from top, vmstat, dmesg, uptime, all at once, instead of individually?
